[package]
name = "test_results_parser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "test_results_parser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.1"
quick-xml = "0.31.0"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
