on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install requirements
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install maturin
          pip install -r tests/requirements.txt
          maturin develop
      - name: Run tests
        run: |
          . venv/bin/activate
          python -m pytest